# -*- coding: utf-8 -*-
"""MVP SSD Danilo (180111256).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FELZNJfCM__ii6jYGAcgWGfr3fz90eaQ

# Projeto de Machine Learning – Eficiência Energética de Edificações

## Contexto

O consumo energético em edificações é um fator essencial para eficiência operacional e sustentabilidade. Neste trabalho, busca-se analisar e prever o consumo energético com base em características estruturais.

Inspirado em conceitos de Controle Estatístico de Processo (CEP), este estudo também analisa a variabilidade dos dados e o comportamento do processo.

## Formulação do Problema

Trata-se de um problema de aprendizado supervisionado, no qual deseja-se aprender uma função f(X) → Y, onde:

- X: características das edificações
- Y: consumo energético (Heating Load)

O objetivo é construir um modelo capaz de generalizar para novos dados.

Dataset: https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx

## Hipóteses

- Características estruturais influenciam o consumo energético
- Existe variabilidade significativa no processo
"""

# IMPORTAÇÃO E DADOS

import pandas as pd
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx"
df = pd.read_excel(url)

df.head()

# EXPLORAÇÃO DOS DADOS

df.info()
df.describe()
df.isnull().sum()

"""O dataset contém variáveis relacionadas às características físicas das edificações e duas variáveis alvo:

- Y1: Heating Load
- Y2: Cooling Load
"""

# PRÉ-PROCESSAMENTO

df = df.dropna()

X = df.drop(['Y1','Y2'], axis=1)
y = df['Y1']

# TREINO E TESTE

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ANÁLISE EXPLORATÓRIA

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(data=df[['Y1','Y2']])
plt.title("Variabilidade do consumo energético")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlação entre variáveis")
plt.show()

"""Observa-se variabilidade significativa nos dados, indicando diferenças no comportamento energético das edificações, o que é compatível com sistemas reais."""

# MODELAGEM

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor

model1 = LinearRegression()
model2 = RandomForestRegressor()
model3 = DecisionTreeRegressor()
model4 = KNeighborsRegressor()

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)
model4.fit(X_train, y_train)

# AVALIAÇÃO

from sklearn.metrics import mean_squared_error, r2_score

models = {
    "Linear Regression": model1,
    "Random Forest": model2,
    "Decision Tree": model3,
    "KNN": model4
}

for name, model in models.items():
    pred = model.predict(X_test)
    print(f"\n{name}")
    print("MSE:", mean_squared_error(y_test, pred))
    print("R2:", r2_score(y_test, pred))

# VALIDAÇÃO CRUZADA

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model2, X, y, cv=5)

print("Scores:", scores)
print("Média:", scores.mean())
print("Desvio:", scores.std())

"""A validação cruzada fornece uma estimativa mais robusta da capacidade de generalização do modelo."""

# OTIMIZAÇÃO

from sklearn.model_selection import GridSearchCV

params = {'n_estimators':[50,100,150]}

grid = GridSearchCV(RandomForestRegressor(), params)
grid.fit(X_train, y_train)

print("Melhores parâmetros:", grid.best_params_)

# IMPORTÂNCIA DAS VARIÁVEIS

import pandas as pd

importances = model2.feature_importances_
features = X.columns

df_imp = pd.DataFrame({'Feature':features,'Importance':importances})
df_imp.sort_values(by='Importance', ascending=False)

"""**ANÁLISE (OVERFITTING / UNDERFITTING)**

Modelos mais complexos, como Random Forest, apresentam maior capacidade de capturar padrões, porém podem sofrer overfitting.

Modelos simples podem apresentar underfitting, não capturando a complexidade do problema.

O equilíbrio entre viés e variância é essencial para um bom desempenho.

**CONCLUSÃO**

O modelo Random Forest apresentou melhor desempenho entre os avaliados, indicando maior capacidade preditiva.

A validação cruzada confirmou a robustez do modelo, demonstrando boa capacidade de generalização.

Observa-se que o consumo energético depende significativamente das características estruturais das edificações.

A análise baseada em conceitos de Controle Estatístico de Processo mostrou variabilidade relevante, indicando a importância do monitoramento contínuo.
"""